[uwsgi]
module = vinnyexpres.app
callable = app
processes = 3

master = true
cheap = true
need-app = true
vacuum = true

buffer-size = 65535

log-format = [wid: %(wid)|pid: %(pid)] %(addr) (%(user)) [%(vars) vars in %(pktsize) bytes] [%(ctime)] %(method) %(uri) => generated %(rsize) bytes in %(msecs) msecs (%(proto) %(status)) %(headers) headers in %(hsize) bytes (%(switches) switches on core %(core))
