{{- if not .Values.email.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vinnyexpres.emailSecret" . }}
  labels:
    {{- include "vinnyexpres.labels" . | nindent 4 }}
type: Opaque
stringData:
  EMAIL_FROM_PASS: {{ .Values.email.password | quote }}
{{- end }}
